// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    // ignore: missing_enum_constant_in_switch
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
    }

    throw UnsupportedError(
      'DefaultFirebaseOptions are not supported for this platform.',
    );
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDw0s5S2MY1vqLxOW_g8I02SXMVKGsNYds',
    appId: '1:974885514746:web:38c61301563eb4eac10843',
    messagingSenderId: '974885514746',
    projectId: 'wasteagram-23643',
    authDomain: 'wasteagram-23643.firebaseapp.com',
    storageBucket: 'wasteagram-23643.appspot.com',
    measurementId: 'G-KQ0G6X64MH',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDP5W6YU49bv10FcGADTG9nCRBJ0DmPUIM',
    appId: '1:974885514746:android:5bffea9cd495e006c10843',
    messagingSenderId: '974885514746',
    projectId: 'wasteagram-23643',
    storageBucket: 'wasteagram-23643.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC6CFiQF5d4GIbXECkiGUoqS5SVpRoaHAs',
    appId: '1:974885514746:ios:d5274bb4972c3658c10843',
    messagingSenderId: '974885514746',
    projectId: 'wasteagram-23643',
    storageBucket: 'wasteagram-23643.appspot.com',
    iosClientId: '974885514746-4iludu95faukj4tejsitkpari1f27ba1.apps.googleusercontent.com',
    iosBundleId: 'com.example.wasteagram',
  );
}
